name: Main Workflow

on:
  push:
    name: Main Workflow Push
    branches: [ main ]
  pull_request:
    name: Main Workflow PR
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test and Analyze
    steps:
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

